**Write a NumPy program to reshape this 1D array [1 2 3 4 5 6] into a 2D array with 2 rows.**

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 3))

print(arr)

[[1 2 3]
 [4 5 6]]


**Write a NumPy program to perform matrix multiplication between a 3x3 matrix and a 3x2 matrix**

In [5]:
import numpy as np

# Define the matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8], [7, 6], [5, 4]])

# matrix multiplication
result = np.dot(matrix1, matrix2)

# Print the matrix result
print(result)

[[ 38  32]
 [101  86]
 [164 140]]


**Write a NumPy program to find the most frequent value and the number of times it occured in the array**

[

[1, 2, 3, 2, 1],
[4, 2, 5, 2, 6],
[2, 1, 2, 3, 2],
[7, 2, 8, 2, 9]  
]

In [8]:
import numpy as np  # Import the NumPy library

# Define the array
arr = np.array([[1, 2, 3, 2, 1], [4, 2, 5, 2, 6], [2, 1, 2, 3, 2], [7, 2, 8, 2, 9]])

# Flatten the array into a 1D array
flat_arr = arr.flatten()

# Get unique values and their counts
unique_vals, counts = np.unique(flat_arr, return_counts=True)

# Find the index of the most frequent value
most_frequent_index = np.argmax(counts)

# Get the most frequent value using the index
most_frequent_val = unique_vals[most_frequent_index]

# Get the count of the most frequent value
most_frequent_count = counts[most_frequent_index]


print("Most frequent value:", most_frequent_val)
print("Number of times it occurred:", most_frequent_count)

Most frequent value: 2
Number of times it occurred: 9


**Write a program that takes a NumPy array representing a dataset with a column of dates and create a new column extracting the month of each date.**

np.array([

('2024-01-15', 10, 100),

('2024-02-28', 15, 150),

('2024-03-10', 20, 200),

('2024-04-22', 25, 250),

('2024-05-05', 30, 300),

('2024-06-18', 35, 350),

('2024-07-30', 40, 400),

('2024-08-12', 45, 450),

('2024-09-25', 50, 500),

('2024-10-07', 55, 550)
]

In [9]:
import numpy as np

data = np.array([
    ('2024-01-15', 10, 100),
    ('2024-02-28', 15, 150),
    ('2024-03-10', 20, 200),
    ('2024-04-22', 25, 250),
    ('2024-05-05', 30, 300),
    ('2024-06-18', 35, 350),
    ('2024-07-30', 40, 400),
    ('2024-08-12', 45, 450),
    ('2024-09-25', 50, 500),
    ('2024-10-07', 55, 550)
])

months = [int(date.split('-')[1]) for date in data[:, 0]]
new_data = np.column_stack((data, months))

print(new_data)

[['2024-01-15' '10' '100' '1']
 ['2024-02-28' '15' '150' '2']
 ['2024-03-10' '20' '200' '3']
 ['2024-04-22' '25' '250' '4']
 ['2024-05-05' '30' '300' '5']
 ['2024-06-18' '35' '350' '6']
 ['2024-07-30' '40' '400' '7']
 ['2024-08-12' '45' '450' '8']
 ['2024-09-25' '50' '500' '9']
 ['2024-10-07' '55' '550' '10']]


**Given a NumPy array representing a dataset with missing values, write a program to replace all the missing values (NaNs) with the mean of the respective column.**

[ [ 1. 2. nan 4. 5.],

[ 6. nan 8. 9. 10.],

[11. 12. 13. nan 15.],

[16. 17. nan 19. 20.],

[nan 22. 23. 24. 25.] ]**

In [7]:
import pandas as pd

data = pd.DataFrame([
    [1., 2., np.nan, 4., 5.],
    [6., np.nan, 8., 9., 10.],
    [11., 12., 13., np.nan, 15.],
    [16., 17., np.nan, 19., 20.],
    [np.nan, 22., 23., 24., 25.]
])

data = data.fillna(data.mean())  # Replace NaNs with column means

print(data)

      0      1          2     3     4
0   1.0   2.00  14.666667   4.0   5.0
1   6.0  13.25   8.000000   9.0  10.0
2  11.0  12.00  13.000000  14.0  15.0
3  16.0  17.00  14.666667  19.0  20.0
4   8.5  22.00  23.000000  24.0  25.0
